### ISSUE TITLE
Don't work in actions

### ISSUE THREAD

**Issue by 4n70w4** [spatie/nova-tags-field#105]
Reopen https://github.com/spatie/nova-tags-field/issues/72

**Comment by looksystems** [comment]
Looking at the error message in js console, it looked to me like the tags property isn't initialised because there is no model to bind to in an action field.

My workaround was to set the default tags to an empty array:

            Tags::make('Tags')->default([])

Hope that helps.

**Comment by nilsE** [comment]
This solutions seems to work, thanks.
Could the changes to fillAttributeFromRequest() be included in the next version? Then the tag field would also work in actions out of the box :-)

**Comment by 4n70w4** [comment]
Still don't work without workaround.
