### ISSUE TITLE
Auth conflict w/ Laravel Sanctum

### ISSUE THREAD

**Issue by scadh** [spatie/nova-tags-field#106]
I am experiencing a conflict between Sanctum and Nova Tags Field. When entering text into a Tags: field in my Article resource, the call to '/nova-vendor/nova-tags-field?stuff' is returning 'Unauthorized'. It then unceremoniously drops my session and logs me out. My main routes/api.php middleware group (Route::group(['middleware' => ['auth:sanctum']]) is being bypassed or else it doesn't authorize the request.

I have tried many potential fixes without success, including:

- extending Spatie\TagsField\TagsFieldServiceProvider with my own implementation and removing the 'api' middleware
- adding the 'auth:sanctum' to the route in that extended class
- adding the Spatie route (Route::get('/', \Spatie\TagsField\Http\Controllers\TagsFieldController::class.'@index')) to my own routes/api.php file and loading that file in the extended class

After trying some of the solutions, the tag lookup that happens on keypress in a Tags:: field still doesn't return any matching tags, but I can type a value in and submit the Article. However, neither the tag nor any relationship to the Article is saved. I have seen several different errors, most often just 401 Unauthorized. But some combinations of the fixes above have returned errors like:

```
"message": "Too few arguments to function Illuminate\\Auth\\Middleware\\Authorize::handle(), 2 passed in /home/vagrant/gtb-bca-drive/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php on line 167 and exactly 3 expected",
    "exception": "ArgumentCountError",
    "file": "/home/vagrant/gtb-bca-drive/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php",
    "line": 41,
```
Not sure where to go from here. I love the Spatie tags Nova presentation layer and don't want to have to roll my own, but I need for it to work with Sanctum, which is a requirement for my project. Any advice would be greatly appreciated.

**Comment by scadh** [comment]
Naturally, I found and fixed the issue within 5 minutes of posting this.  It's plain to see in the code block above. Embarrassingly, It turns out that:

/Illuminate/Auth/Middleware/Authorize !== Spatie\TagsField\Http\Middleware\Authorize

Closing.

**Comment by charlesVandeplassche** [comment]
@scadh can you explain how you fixed this? I'm facing the same issue.
