### ISSUE TITLE
Customise the store method.

### ISSUE THREAD

**Issue by danmatthews** [spatie/nova-tags-field#12]
Would be awesome if, in the same way you can with the `File` nova fields, you could customise the `store()`, `preview()`, `resolveWith` etc methods.

I have a client site that has tags already, and i'd love to add this in, but it would have to work with their current setup in the database.

I might look at contributing this as a feature but i thought i'd better ask if you're open to it first rather than wasting time on a PR that might get rejected!

Dan.

**Comment by freekmurze** [comment]
I'm open for a PR if it's simple enough for me to maintain, and the docs/tests are updated. 👍
