### ISSUE TITLE
not working with laravel 8 and nova v3.27.0

### ISSUE THREAD

**Issue by haythoo** [spatie/nova-tags-field#126]
Hi,
I'm trying to use this package in a fresh laravel 8 project with nova v3.27.0. 

I followed all the steps, but I'm facing this problem, I'm getting two errors notifications:

<img width="1059" alt="Screen Shot 2021-07-16 at 10 37 54 PM" src="https://user-images.githubusercontent.com/3076507/126000228-b7eafa35-5b68-452b-b7e1-1776d62d7925.png">

From laravel debug bar:
<img width="563" alt="Screen Shot 2021-07-16 at 10 38 19 PM" src="https://user-images.githubusercontent.com/3076507/126000254-5a2b417e-3c65-4c3e-bf06-b539cc7f2ca2.png">

**Comment by haythoo** [comment]
Any suggestions ?

**Comment by haythoo** [comment]
another screenshot of the problem, once I enter any character in the tags box, I got this error:

<img width="1679" alt="Screen Shot 2021-07-23 at 3 33 15 AM" src="https://user-images.githubusercontent.com/3076507/126725186-ac536882-c409-40e5-84ec-76aaff1c189f.png">

**Comment by haythoo** [comment]
This solution worked for me:

https://github.com/spatie/nova-tags-field/issues/87#issuecomment-730714663

**Comment by aliwesome** [comment]
I'm facing the same issue.
