### ISSUE TITLE
Escaping the tag names on field resolution causes discoverability problems on field save

### ISSUE THREAD

**Issue by mrdj07** [spatie/nova-tags-field#128]
![image](https://user-images.githubusercontent.com/400701/129979682-180d9a55-3793-4b59-beae-86ec6eb81a2b.png)
I don't understand why the resolver escapes the name of the tag, but the TagsFieldController doesn't escape them. 

This results in a correct first presentation of the Tags and saves as expected, but after a reload of the entity form page, it screws up the display of the tag name and it becomes impossible to save the entity with an escaped Tag.

![image](https://user-images.githubusercontent.com/400701/129982266-ffced8d2-78a7-4892-8c92-b80f04f6e671.png)

Removing the escaping of the tag names works really well, so why are they escaped ?

**Comment by freekmurze** [comment]
Fixed in latest release
