### ISSUE TITLE
Editing tags on a model does not trigger the updated method on model observer

### ISSUE THREAD

**Issue by 1stevengrant** [spatie/nova-tags-field#136]
I have a `Video` model that has tags associated with it. When I add/remove tags on the model, my `VideoObserver` `updated` method never fires.

I mean, I guess that kind of makes sense because tags aren't directly being touched on the `Video` model itself.

Is there a way I could implement this?

**Comment by freekmurze** [comment]
I'm thinking you could listen for the model events that get fired when new tags get added or associated.
