### ISSUE TITLE
Respect Laravel Nova's resource policy for Tag

### ISSUE THREAD

**Issue by vaites** [spatie/nova-tags-field#143]
If you create a Laravel Nova resource for the Tag model [as explained here](https://github.com/spatie/nova-tags-field#administering-tags-in-nova),  this field does not respect the associated policy.

The whole field can be shown/hidden using `canSee()` method, but there are cases where the creation of tags is restricted, so the field should respect the policy defined for the Tag resource and not allow adding new tags if the user doesn't have permissions. In this case, it should only let you choose from the tags already created.

As a workaround, a validation rule can be added to check if the user specified new tags and return an error.

**Comment by freekmurze** [comment]
Feel free to submit a PR with tests to fix this 👍

**Comment by vaites** [comment]
OK, give me some days to look for the best solution, because I think it requires both frontend/backend changes and maybe some discussion...
