### ISSUE TITLE
Nova V4 support

### ISSUE THREAD

**Issue by guifarro** [spatie/nova-tags-field#145]
Friendly reminder that Laravel Nova V4 has been released . [Upgrade guide](https://nova.laravel.com/docs/4.0/upgrade.html).

BTW Amazing work , thanks a lot.

**Comment by freekmurze** [comment]
We'll work on this soon. If you need this quick, feel free to send a PR 👍

**Comment by guifarro** [comment]
Its working on nova V4, there is some minor aesthetic issues like the lack of color in tag suggestions and the added tags in forms
