### ISSUE TITLE
Using multiple tag types are not supported

### ISSUE THREAD

**Issue by hubertnnn** [spatie/nova-tags-field#15]
If I add more than 1 tag type to the same model it will use only the last one and duplicate the values to other types.
eg:
    Tags::make('Categories', 'tags')->type(Models\Tag::TYPE_CATEGORY),
    Tags::make('Themes', 'tags')->type(Models\Tag::TYPE_THEME),
    Tags::make('Custom tags', 'tags')->type(Models\Tag::TYPE_CUSTOM),

If I set 
- categories to Category1, Category2
- themes to Theme1, Theme2
- Custom tags to Custom1, Custom2

it will create following tags and assign to model:
- type: category value:Custom1
- type: category value:Custom2
- type: theme value:Custom1
- type: theme value:Custom2
- type: custom value:Custom1
- type: custom value:Custom2

expected values:
- type: category value:Category1
- type: category value:Category2
- type: theme value:Theme1
- type: theme value:Theme2
- type: custom value:Custom1
- type: custom value:Custom2

**Comment by rubenvanassche** [comment]
Hi hubertnnn,

I think you made a mistake in your code, this should solve your issue:
``
Tags::make('Categories')->type(Models\Tag::TYPE_CATEGORY),
Tags::make('Themes')->type(Models\Tag::TYPE_THEME),
Tags::make('Custom tags')->type(Models\Tag::TYPE_CUSTOM),
``

**Comment by hubertnnn** [comment]
Wont this require me to make 3 custom relationships:
```
    public function categories(): MorphToMany
    {
        return $this
            ->tags()
            ->where('type', Tag::TYPE_CATEGORY);
    }

    public function themes(): MorphToMany
    {
        return $this
            ->tags()
            ->where('type', Tag::TYPE_THEME);
    }

    public function customTags(): MorphToMany
    {
        return $this
            ->tags()
            ->where('type', Tag::TYPE_CUSTOM);
    }
```

Btw. This is the workaround I am using for now.

**Comment by nickpoulos** [comment]
That is a really lame workaround, why even have a `type` method if it's really just useless?
