### ISSUE TITLE
[feature] auto split strings with comma

### ISSUE THREAD

**Issue by S-anasol** [spatie/nova-tags-field#19]
Hi, one of my site editors extremely lazy.

So he use Ctrl C with long strings divided by comma with many tags and Ctrl V it to tag field, then result is single loooooong tag.
![image](https://user-images.githubusercontent.com/1709666/46337356-00473380-c636-11e8-8580-6ed8beaea0d7.png)

So I think would be great add some magic like Ctrl V listener and split strings with commas into multiple tags automatically.

**Comment by cfreear** [comment]
I was about to add a suggestion for this so 👍 from me. Also different "trigger" keys, so instead of pressing enter to add a tag the comma key (or any other) could be used. Any interest in a PR for these @freekmurze ?

**Comment by freekmurze** [comment]
With the comma key used for tag separation how would you create a tag named "Crosby, Stills, Nash & Young"?

**Comment by cfreear** [comment]
The [IETF RFC for the csv format](https://tools.ietf.org/html/rfc4180) states;

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

and;

> If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote.

So a tag named **"Déjà Vu" by Crosby, Stills, Nash & Young** would need to be entered as `previous tag,"""Déjà Vu"" by Crosby, Stills, Nash & Young",next tag`

**Comment by freekmurze** [comment]
Seems pretty grim to require users to type that.

I'm up however for introducing a config setting so users can set their own tag separators. Default should be `, `

**Comment by cfreear** [comment]
I see your point, perhaps this functionality could work ``onpaste``? The use case I'm experiencing that would be solved by this involves a user copying and pasting data from an existing source and it sounds like @S-anasol 's case is the same, I don't think it would be of much use for "typed in" tags.

**Comment by freekmurze** [comment]
I currently don't want to do anything special on paste, could be a can of worms were different groups of users expect different things. Leave it simple for now.
