### ISSUE TITLE
Form field not working

### ISSUE THREAD

**Issue by jorgv** [spatie/nova-tags-field#2]
nova 1.0.6

adding tags from the controller or anywhere in the code works as expected just following spatie/nova-tags-field documentation.

But when trying to add it from Nova, the field doesn't search, add or convert text into to tag.

I don't have any error log.

![image](https://user-images.githubusercontent.com/32174909/44657033-abdbe300-a9fb-11e8-89d9-c20fd0b5c7cf.png)

After updating the new tags are not save

![image](https://user-images.githubusercontent.com/32174909/44657141-2efd3900-a9fc-11e8-85d0-b3f85b42467c.png)

**Comment by freekmurze** [comment]
I can't seem to reproduce this. I'll create a tag for the current master version, try upgrading to that version. If it fails there, feel free to submit a PR.
