### ISSUE TITLE
Tag tips for Russian do not work

### ISSUE THREAD

**Issue by abordage** [spatie/nova-tags-field#21]
This bug is related to spatie/laravel-tags, but the screenshots and logic for nova-tags-field.

**Search tags in English works:**

![tag01](https://user-images.githubusercontent.com/28537731/46403361-fc391580-c70a-11e8-917a-9150172cf65f.png)

**If you use Russian - broken encoding(in query):**

![tag02](https://user-images.githubusercontent.com/28537731/46403369-ffcc9c80-c70a-11e8-91a6-a5dea147051a.png)

**From mysql log:**

![2018-10-03_125349](https://user-images.githubusercontent.com/28537731/46403535-74074000-c70b-11e8-98cf-8808542de816.png)

**If you change the line in spatie\laravel-tags\src\Tag.php:**

`return $query->whereRaw('LOWER(JSON_EXTRACT(name, "$.' . $locale .'")) like ?', ['"%' . strtolower($name) . '%"']);`

on:

`php
return $query->whereRaw('LOWER(JSON_EXTRACT(name, "$.' . $locale .'")) like ?', ['"%' . mb_strtolower($name) . '%"']);`

working

![tag03](https://user-images.githubusercontent.com/28537731/46403399-0fe47c00-c70b-11e8-8071-f2ad4c793cf4.png)

**This error appeared in nova 1.1.4, previously worked fine

**Comment by freekmurze** [comment]
Feel free to send a PR that fixes this!
