### ISSUE TITLE
Autocomplete error - column \"$.en-GB\" does not exist - Postgres

### ISSUE THREAD

**Issue by robbydooo** [spatie/nova-tags-field#22]
I am getting the following error on a fresh install of this package on a Postgres database.
Whenever I start typing in the field, the autocomplete requests 500 with:

```
"message": "SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"$.en-GB\" does not exist\nLINE 1: ...lect * from \"tags\" where LOWER(JSON_EXTRACT(name, \"$.en-GB\")...\n                                                             ^ (SQL: select * from \"tags\" where LOWER(JSON_EXTRACT(name, \"$.en-GB\")) like \"%news%\" and \"type\" = blog and \"type\" = blog limit 5)",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "xxxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 664,
```

It doesn't actually stop me from adding the tags but the auto complete does not work.
Let me know if I can provide any additional detail.

**Comment by jesseschutt** [comment]
I've bumped into this as well and it's due to Spatie\Tags only being supported on MySql. I'm currently looking at what it would take to add postgres support, but am unsure whether a PR would be accepted.

**Comment by robbydooo** [comment]
I don't believe this package is intended to be Mysql only. The requirements suggest " a database that supports JSON fields and functions such as MySQL 5.7 or higher."

Postgres supports JSON fields perfectly well.

**Comment by jesseschutt** [comment]
Take a look here: https://github.com/spatie/laravel-tags/blob/47946dd12b3d2b3adba624d9ea85d71534533094/src/Tag.php#L33

As I understand it, that is a Mysql-specific syntax for parsing a value out of the JSON content. That method is what is causing the error you are seeing.

**Comment by jesseschutt** [comment]
Also - https://github.com/spatie/laravel-tags/issues/134#issuecomment-424974319

**Comment by freekmurze** [comment]
Because for our projects we don't use Postgres, we don't want to maintain any specific Postgres code. Feel free to fork our code and create a version that works for you.
