### ISSUE TITLE
Adding new tags on the fly

### ISSUE THREAD

**Issue by v1nk0** [spatie/nova-tags-field#26]
It seems that I can only add tags that are already present. 
When I start to type a new tag within the "add tags" field, nothing happens and nothing get's saved.
Only, when I add the tag first (e.g. using the tag resource) I can add the tag using the suggestions.

Is this intended behaviour? I would expect the suggestions to show existing tags, but nonetheless be able to add a tag that is not present yet, which will in this case be created.

**Comment by freekmurze** [comment]
This isn't intended behaviour, any new tags should get saved. In my Nova powered admins this works perfectly.

**Comment by v1nk0** [comment]
Yes, it works.
I've tried 'tab', 'comma' and 'space' but somehow I forgot to try 'enter'.
For anyone experiencing the same: press 'enter' to transform the text-input into a "tag".

**Comment by freekmurze** [comment]
I'd accept a PR that makes the tag completion key(s) configurable.

**Comment by araeuchle** [comment]
> @freekmurze Yes, it works.
> I've tried 'tab', 'comma' and 'space' but somehow I forgot to try 'enter'.
> For anyone experiencing the same: press 'enter' to transform the text-input into a "tag".

I was running in the same situation. Enter worked for me as well. maybe this should mentioned somewhere in the docs? also 'd be cool if there would be more ways to add a tag like with , or space tab

**Comment by freekmurze** [comment]
Feel free to send a PR to make the keys configurable and/or to make the docs more clear.
