### ISSUE TITLE
not loading vue component?

### ISSUE THREAD

**Issue by mniblett** [spatie/nova-tags-field#27]
Several things going wrong:
1. The tag field is showing up in the index view, I beleive it should only be in the detail view like other one-many, many-many fields.
2, After pushing it to detail view with hidefromindex(), it's lumped in with the other fields, no styling, no 'add tag" link.

Should the javascript have been copied into my resources folder or is it OK for it to be in the vendor folder? It wasn't in my javascript directory (I ran npm istall and npm run dev after composer require spatie/nova-tags-field).

Not sure what to do next but looks like something went wrong during the install and it's not seeing the vue component.

Thanks for any help and putting out such great packages!

**Comment by rubenvanassche** [comment]
Hi @mniblett can you provide me a demo application showing that the vue component isn't loading? I've just checked and everything is working fine here.
