### ISSUE TITLE
not allow to store the tag field data with mariaDB

### ISSUE THREAD

**Issue by yatin13490** [spatie/nova-tags-field#32]
Hey,

I just follow all the steps as mention in the document, but when I tried to store the tag's data it gives me error,

I am not getting what is the issue with it, can anybody guide me in this.
![screenshot-seasons sr-2018 11 28-19-04-43](https://user-images.githubusercontent.com/6308981/49155391-d4e47a80-f340-11e8-8ea9-0c8ccb91cf82.png)

I used the 10.2.19-MariaDB

**Comment by cfreear** [comment]
[MySQL 5.7.8 or higher](https://github.com/spatie/nova-tags-field#requirements) only unfortunately.
