### ISSUE TITLE
Adding a non-existing tag does not work

### ISSUE THREAD

**Issue by Naoray** [spatie/nova-tags-field#37]
When adding tags first via the `Tag` resource and then going to e.g. `Post` resource and adding them there works fine. But If I want to add tags right from the `Post` resource it does not. Not sure if this is intended behaviour?!

![tags-bug](https://user-images.githubusercontent.com/10154100/50477757-fda67100-09cd-11e9-9970-8cfc03fcad1e.gif)

**Comment by sebastiandedeyne** [comment]
You need to hit <kbd>enter</kbd> before saving. The tag needs to be wrapped in a blue box to actually be persisted. 

Might be a good idea to add some sort of placeholder with the new tag below so you can click to add like the suggestions. PR's welcome!

**Comment by Naoray** [comment]
:see_no_evil:  sorry! Works
