### ISSUE TITLE
Using nova tags in a BelongsToMany relationship

### ISSUE THREAD

**Issue by Elandlord** [spatie/nova-tags-field#45]
Hi,

I was playing around with this package, and I would like to add this functionality to a belongsToMany relationship.

```
BelongsToMany::make('Website')
    ->fields(function () {
        return [
            Tags::make('Tags'),
        ];
   }),
```

In this specific case, I have added the `HasTags` trait to the intermediary model. In this case, it prompts me with: `Call to a member function map() on null`.

![Schermafbeelding 2019-03-21 om 15 38 19](https://user-images.githubusercontent.com/5966835/54760032-890b5900-4bef-11e9-9b13-0a0e8835dda1.png)

Is there anyone that can shine some light on this situation, perhaps a working example?

Thanks in advance!

**Comment by LorenzoSapora** [comment]
While not reopening this issue, I've just hit it myself. I'll log any solutions for any future spelunkers.

**Comment by LorenzoSapora** [comment]
**Update:** This is a conflict with another package. In my case it was nova-flexible-content. This can also happen to other spatie packages, but the issue mostly lies with how flexible-content's resolver works. Hope this helps.
