### ISSUE TITLE
Conflict with base model saved hook

### ISSUE THREAD

**Issue by flearsmedia** [spatie/nova-tags-field#47]
Hi there,

my base model uses the saved hook to sync the model data with an external service.

Since this package saves the tags also within this exact cycle all the attributes arrive at the external service except for the tags as they have most likely not yet been saved in the database/attributes at this very point of time.

I have been struggling to come up with a satisfying workaround and was wondering if you guys have any ideas - either to optimize the tags being saved before the saved hook starts or any other implementation on my side to make sure the tags are also sent to the service.

Thanks a lot!

**Comment by freekmurze** [comment]
I haven't run into this problem and currently can't offer any ideas on how to solve it. Feel free to submit a PR.

**Comment by flearsmedia** [comment]
Solved by implementing a publish field where the model has to be saved before and then will be synced once published.

Thanks for the great package!

**Comment by LorenzoSapora** [comment]
While not reopening this issue, I've just hit it myself. I'll log any solutions for any future spelunkers.
