### ISSUE TITLE
Composer: requires laravel/nova ^2.0 -> no matching package found.

### ISSUE THREAD

**Issue by SamBellerose** [spatie/nova-tags-field#52]
When running composer `require spatie/nova-tags-field` I get the following error

```
Problem 1
    - Installation request for spatie/nova-tags-field ^2.2 -> satisfiable by spatie/nova-tags-field[2.2.0].
    - spatie/nova-tags-field 2.2.0 requires laravel/nova ^2.0 -> no matching package found.
```

Here's what my composer.json looks like

```
"require": {
        "php": "^7.1.3",
        "barryvdh/laravel-cors": "^0.11.3",
        "doctrine/dbal": "^2.9",
        "laravel/framework": "5.8.*",
        "laravel/nova": "*",
        "laravel/tinker": "^1.0",
        "renatomarinho/laravel-page-speed": "^1.8",
        "spatie/eloquent-sortable": "^3.6",
        "spatie/geocoder": "^3.4",
        "spatie/laravel-tags": "^2.4",
    },
    "minimum-stability": "dev",
    "prefer-stable": true
``` 
I have installed Nova by dragging the folder inside my vendor directory. Do I have to put a specific version for laravel/nova in my composer.json? It seems like it's not recognizing the package.

*EDIT*

When changing the version for laravel/nova -> "^2.0"
I get the following error:
```
Problem 1
    - The requested package laravel/nova ^2.0 exists as laravel/nova[9999999-dev] but these are rejected by your constraint.
```

Thanks for any help!

**Comment by curder** [comment]
I have the same error information.

It's there anyone give me some help?

```
 "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/nova": "^2.0",
        "laravel/tinker": "^1.0",
        "spatie/laravel-tags": "^2.4"
    },
```
when I run `composer require spatie/nova-tags-field`, I got the following errors:

![image](https://user-images.githubusercontent.com/8327004/62412229-deda1e00-b631-11e9-94d7-b618b9fc62b6.png)

Thanks. 🧐

**Comment by phuclh** [comment]
I have the same problem here.

**Comment by devilstars** [comment]
Go to **/nova** folder and add `"version": "2.0",` in **composer.json** file.
