### ISSUE TITLE
Suggestions Not Working With Postgres

### ISSUE THREAD

**Issue by nickpoulos** [spatie/nova-tags-field#54]
Using psql (PostgreSQL) 10.9 the suggestions query fails with a 500 error due to Postgres not supporting the JSON_EXTRACT function found in the raw queries in Tag.php and HasTag.php. 

The solutions are not as nice and neat as you would hope due to the differing ways Postgres/MySql implement their JSON functions, and the lack of an "ILIKE" operator in MySql. 

The only way I see that will allow the use of an case-insensitive search of the tag name/slug would be to check the user's DB_DRIVER and select the correct raw query accordingly. 

If that sounds ok to you guys I would be happy to submit PR.

**Comment by freekmurze** [comment]
We’re currently only using MySQL for our projects. For us it’s fine to us MySQL only functions.

**Comment by nickpoulos** [comment]
Yes that may be, but for others who use Postgres, the requirements for the underlying spatie/laravel-tags package should be updated to set a hard requirement for MySql.  As it reads now is misleading. 

> This package requires Laravel 5.8 or higher, PHP 7.2 or higher and a database that supports json fields and functions such as MySQL 5.7 or higher.

Postgres supports JSON fields and functions, just not the exact MySql ones.
