### ISSUE TITLE
Installed Nova manually so cant upgrade...

### ISSUE THREAD

**Issue by leeovery** [spatie/nova-tags-field#57]
Hey,

Getting the following when trying to upgrade this package:

```
spatie/nova-tags-field 2.2.1 requires laravel/nova ^2.0 -> no matching package found.
```

I installed nova the manual way. Perhaps we can remove the requirement for Nova. I think its implied and people won't be using this without it anyway.

Unless there's another way around this issue?

Thanks!!!
Lee

**Comment by pleone** [comment]
Same problem here, can't even require this package

**Comment by pleone** [comment]
https://github.com/spatie/nova-tags-field/issues/52

This workaround could help even if it's not the best approach.
