### ISSUE TITLE
Displayed tags don't take type into account

### ISSUE THREAD

**Issue by depsimon** [spatie/nova-tags-field#6]
I'm using Tags on Leads models and they have 2 kind of tags: categories and keywords.

However both `Tags::make('Categories')->type('category')` and `Tags::make('Keywords')->type('keyword')` display the same tags. (all of them)

I resolved the issue by taking the type into account in the `resolveAttribute` method of the Tags Field class.

**Comment by freekmurze** [comment]
Thanks!
