### ISSUE TITLE
Exception for array_has() after updating to Laravel 6

### ISSUE THREAD

**Issue by SunnyDayGuide** [spatie/nova-tags-field#65]
Since the latest Laravel update has dropped support for the string and array helpers, I am now getting an exception when using the tags field:

Call to undefined function array_has() ../vendor/spatie/nova-tags-field/src/Tags.php#82

Any plans to use the Illuminate\Support\Arr class here?

**Comment by freekmurze** [comment]
I accept a PR that fixes this.

**Comment by vdbelt** [comment]
Since you are getting this error on line 82, it indicates to me your are using version 2.1 of this package. 

The helpers were already replaced in the latest version (2.3). 
Could you upgrade and see if it works for you?

**Comment by ManojKiranA** [comment]
@SunnyDayGuide can you specify the Package version you are using
