### ISSUE TITLE
routes nova-vendor/spatie/nova-tags-field?filter returned 404

### ISSUE THREAD

**Issue by Neticx** [spatie/nova-tags-field#66]
i have read and following all instruction given in README, also i have following the installation instruction in docs of laravel tags packages. but when i trying to typing on tags field in my nova resource. i got nothing. when i check the network in the chrome console. i got 404 on https://myapp.local/nova-vendor/spatie/nova-tags-field?filter[containing]=sometags&limit=5.
anyone who understand this problems?

**Comment by pmreyes** [comment]
Hi @Neticx how have you managed to resolve this? I'm getting the same error.
