### ISSUE TITLE
nova-tags-field in nova action

### ISSUE THREAD

**Issue by parelius** [spatie/nova-tags-field#72]
I'd like to use the nova-tags-field in a nova action.
When trying to do this I get an error message:
`Undefined property class@anonymous::$tags`.

My action:

```
namespace App\Nova\Actions;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Collection;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;
use Spatie\TagsField\Tags;

class UpdatePhotoContent extends Action
{
    use InteractsWithQueue, Queueable;

    public function handle(ActionFields $fields, Collection $models) {
//...
}

public function fields()
    {
        return [
//...
          Tags::make(__('tags.tags')),
        ];
    }
}
```

My Nova Resource:

```
class Photo extends Resource
{
   //...

       public function actions(Request $request)
    {
        return [
          new Actions\UpdatePhotoContent,
        ];
    }
}
```

Any idea, what could be wrong here?
Should actions work with this field or is something missing?
I have no problem using other Nova fields in actions, at all.
Thanks!

**Comment by ashestree87** [comment]
I am getting the same issue when trying to use the tags field on an action. Did anyone work this out?

**Comment by 4n70w4** [comment]
The same issue!

**Comment by AstroCorp** [comment]
+1

**Comment by looksystems** [comment]
Reposting workaround from #105...

Looking at the error message in js console, it looked to me like the tags property isn't initialised because there is no model to bind to in an action field.

My workaround was to set the default tags to an empty array:

            Tags::make('Tags')->default([])

And I had to override this Tags method:

    protected function fillAttributeFromRequest(NovaRequest $request, $requestAttribute, $model, $attribute)
    {
        $requestValue = $request[$requestAttribute];
        $tagNames = explode('-----', $requestValue);
        $tagNames = array_filter($tagNames);

        $class = get_class($model);

        if (method_exists($class, 'saved')) {
            $class::saved(function ($model) use ($tagNames) {
                $model->syncTagsWithType($tagNames, $this->meta()['type'] ?? null);
            });
        } else {
            $model->{$attribute} = $tagNames;
        }
    }

The ActionFields in the handle method then contains an array of tag names which you can apply to models:

    public function handle(ActionFields $fields, Collection $models)
    {
        $tagNames = $fields->tags;

        foreach ($models as $model) {
            try {
                $model->syncTagsWithType($tagNames, $this->meta()['type'] ?? null);
                $this->markAsFinished($model);
            } catch (\Exception $e) {
                $this->markAsFailed($model, $e);
            }
        }
    }

Hope that helps.
