### ISSUE TITLE
Tags Resource Relations

### ISSUE THREAD

**Issue by Milkhan** [spatie/nova-tags-field#75]
I've created a Tag resource as suggested in the documentation. But in the example, there is only the name field. I would like to list all relations on tag's view, like we do with HasMany::make('Model'). 
Does anyone know how can we achieve that?

Thank you.

**Comment by marcoraddatz** [comment]
In your tag model:
```
/**
 * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
 */
public function issues(): MorphToMany
{
    return $this->morphedByMany(Issue::class, 'taggable');
}
```

In your Nova resource:
```
HasMany::make(__('nova/fields.issues'), 'issues', Issue::class)
    ->sortable(),
```
