### ISSUE TITLE
[Bug] Saving model with tags + types, creates duplicate new tags w/ types

### ISSUE THREAD

**Issue by wassim** [spatie/nova-tags-field#79]
I followed the setup instructions but I have a strange behaviour here.

```
Tags::make('Tags')
    ->withLinkToTagResource() 
```

![Capture d’écran 2020-02-15 à 13 26 47](https://user-images.githubusercontent.com/14947638/74587789-3ac92a80-4ff7-11ea-89a7-2e4038336ec2.png)

![Capture d’écran 2020-02-15 à 13 27 32](https://user-images.githubusercontent.com/14947638/74587794-461c5600-4ff7-11ea-9c07-f3c573080999.png)

When I choose tags with types on a model and hit save, it doesn't link the model to the available tags. Instead it creates new tags without types !

![Capture d’écran 2020-02-15 à 13 27 57](https://user-images.githubusercontent.com/14947638/74587798-4d436400-4ff7-11ea-9b65-fcfbfa8bfdd6.png)

@freekmurze Is this a normal behaviour?

**Edit:**

I've found where this comes from in src/Tags.php:

```
$class::saved(function ($model) use ($tagNames) {
    $model->syncTagsWithType($tagNames, $this->meta()['type'] ?? null);
});
```

**$this->meta()['type']** doesn't return the tag's type value.

`Undefined index: type {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined index: type at /.../vendor/spatie/nova-tags-field/src/Tags.php:89)`

**Comment by craigcartmell** [comment]
Yep finding the same issue here.

Laravel Framework 7.11.0
Laravel Nova 3.4
spatie/nova-tag-fields 3.0

**Comment by craigcartmell** [comment]
> Yep finding the same issue here.
> 
> Laravel Framework 7.11.0
> Laravel Nova 3.4
> spatie/nova-tag-fields 3.0

I should not I've also changed the type tags table to be an id which references a new custom `tagTypes` table I created.

I don't think that's what's causing the issue though.

**Comment by salmanhijazi** [comment]
Facing the same issue. But for me, the type is also saved. It simply duplicates everything everytime I submit the update form. There are duplicate entries in tags as well as taggables.

**Comment by salmanhijazi** [comment]
Have either of you, by any chance, extended the Tag class to change the `findFromString` function? I faced the same issue because I had overloaded the function to utilize the "slug" column and that returned null for the nova tag field as it was checking for the name against the slug column. Hope this helps.
