### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rusya1313** [spatie/nova-tags-field#8]
Hi, guys.
Please, add the flexibility to change a placeholder. Now it is hardcoded "Add tag.."
It would be nice if we can define it from Nova field, like this: Tags::make('Skills')->type('skill')->placeholder('Add new skill..');
Thank you.

**Comment by freekmurze** [comment]
Thanks for the suggestion. We're adding some customization options soon.

**Comment by Milkhan** [comment]
@freekmurze Any progress on this?
