### ISSUE TITLE
Tags not searchable

### ISSUE THREAD

**Issue by NormanHuth** [spatie/nova-tags-field#82]
The tags are not searchable, unfortunately.

**Comment by ashestree87** [comment]
Same problem here. They appear in the network response but are not being shown.

**Comment by aghayeff** [comment]
I wondered why automatically we can not display tags, using without ajax? Just clicking to search input and displaying the list of tags...

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by NormanHuth** [comment]
In our case, the problem was that we use tenants. I have extended the package with a config, where you can set another model. PR appears.
