### ISSUE TITLE
What if using multiple taggable tables? 

### ISSUE THREAD

**Issue by aghayeff** [spatie/nova-tags-field#90]
Let's say that I have a `Product` model, includes HasTags trait. So, we can attach tags into `Tags` and `Taggable` tables. But, except tags, Product is also required colors. I know that we can use `->type` and attach colors same as tags. 

What, if we do not want to store colors in `tags` and `taggabe` tables? Instead of to create `colors` and `product_colors`?
Because my colors table has another fields and has a relationship with another table.

**Comment by freekmurze** [comment]
> What, if we do not want to store colors in tags and taggabe tables? Instead of to create colors and product_colors?
Because my colors table has another fields and has a relationship with another table.

This is currently not supported.
