### ISSUE TITLE
Tag slug not generating slug correctly

### ISSUE THREAD

**Issue by admench** [spatie/nova-tags-field#92]
I'm using a custom Tag model extending base model:

```
<?php

namespace App\Models;

use Spatie\Tags\Tag as BaseTag;

class Tag extends BaseTag
{ 
    public function articles()
    {
        return $this->morphedByMany(Article::class, 'taggable');
    }

    public function getArticleCountAttribute()
    {
        return $this->articles()->count();
    }

    public function getUrlAttribute()
    {
        return url('/home/resources/tags/'.$this->slug);
    }
}

```

And when creating a tag in nova either using the `tags field` or directly as a `tag resource` the slug column does not create the object syntax for localization:
Same happens when creating a new tag via `Tinkerwell`.

![Screenshot_2020-07-24_at_16_32_54](https://user-images.githubusercontent.com/672916/88408661-c6778c00-cdcb-11ea-86c9-3701b4bc281a.png)

Newing up a tag using the `spatie tag` model works fine. Any help would be extremely appreciated.
Many thanks
Adam

**Comment by mustafaaloko** [comment]
What version of MySQL are you using and are the columns of `json` type?

**Comment by admench** [comment]
Thanks @mustafaaloko 

MySql `8.0.18` and yes its a `json` column. I used the default spatie migrations.
