### ISSUE TITLE
Call to a member function map() on null

### ISSUE THREAD

**Issue by Nemes1sX** [spatie/nova-tags-field#94]
I get ```call to a member function map() on null``` when i use this tag field package. I'm using Laravel 7.x version and Nova 3.x How fix this issue?

**Comment by Neoglyph** [comment]
Have the same issue on `spatie/laravel-tags 2.6.2` `spatie/nova-tags-field 2.3.4 ` on `Laravel 5.8` with `PHP 7.4.8`

On my instance it's triggered by `->withLinkToTagResource()`. 
Removing `->withLinkToTagResource()` removed the error, but this leaves you with no links to resources.

**Comment by Nemes1sX** [comment]
But it doesn't necessary to create table for tags?

**Comment by Neoglyph** [comment]
> But it doesn't necessary to create table for tags?

No, don't think so.

**Comment by Nemes1sX** [comment]
I don't specyfing any extra attributes to tag field and I still get an error

**Comment by karlshea** [comment]
I'm getting the error when I'm using HasTags on a pivot table. It's in `resolveAttribute`: `$resource->tags` is null.

**Comment by karlshea** [comment]
I can't test, I already refactored that pivot model to be a full class to fix an unrelated issue.

**Comment by SonerOd** [comment]
> Can somebody confirm that #95 fixes this problem?

Yes. I fixed with this solution.

**Comment by Nemes1sX** [comment]
I solved ```call to a member function map() on null``` when i installed neccessary packages correctly and completed other steps. Finally, tags form field is working, but doesn't insert tags data to the appropriate table column. So, I must define relationships between selected tables and tags?

**Comment by freekmurze** [comment]
Fixed in latest release.

**Comment by JurjenRoels** [comment]
I get this issue when using the Tag in the flexible content. If I move the tag outside de flexible content it works.

**Comment by alexdevandrepair** [comment]
> I get this issue when using the Tag in the flexible content. If I move the tag outside de flexible content it works.

Got the same here... Any solution ?

**Comment by LeigerGaming** [comment]
I've wasted over an hour attempting to resolve this issue today, but haven't found a solution :(

spatie/laravel-tags 2.7.2
spatie/nova-tags-field 3.1.1

Laravel Framework 8.40.0

**Call to a member function map() on null**
<snipped>/vendor/spatie/nova-tags-field/src/Tags.php#111
```php
            $tags = $tags->where('type', $this->meta()['type']);
        }
        return $tags->map(function (Tag $tag) {
            return e($tag->name);
        })->values();
    }
```
