### ISSUE TITLE
Display parent resources when viewing a tag

### ISSUE THREAD

**Issue by vbezruchkin** [spatie/nova-tags-field#98]
Hi,

Thanks for the awesome package. 

I wonder if there could be an easy way to display a list of all resources related to a specific tag, when you open details of this tag. For example I have tags field used for News. When opening a tag view, I want to see all news with this tag.

Thanks for advice.

**Comment by kevnk** [comment]
I still would like to know how to do this... essentially the inverse of Tags::make('Tags') - How do I see all the resources attached to a specific tag when viewing that tag in nova

**Comment by kevnk** [comment]
Solution in #75
